version: "3.7"

services:
  application:
    container_name: ${_Values_root_name}-application
    image:  ${_Values_image_repository}${_Values_server_arch}:${_Values_image_tag}
    restart: 'no'
    ports:
      - "${_Values_service_port}:${_Values_service_port}"
    command: ["-Xmx${_Values_resources_requests_memory}"]

    healthcheck:
      test: "curl -f http://localhost:${_Values_service_port}/actuator/health || exit 1"
      interval: 10s
      timeout: 10s
      retries: 5
    volumes:
      - tmp:/tmp
      - applogs:/usr/share/logs
    networks:
      - ${_Values_root_name}-net
    environment:
      #application
      TZ: Europe/Berlin
      quarkus.http.port: "${_Values_service_port}"
      quarkus.http.io-threads: "20"

      #security
      security.authentication.enabled: "false"

      #jaeger
      quarkus.jaeger.service-name: "person-service"

      quarkus.jaeger.endpoint: "http://${_Values_host_docker_internal}:14268/api/traces"
      quarkus.jaeger.sampler-type: "probabilistic"
      quarkus.jaeger.sampler-param: "1"
      quarkus.jaeger.propagation: "b3"

      #persistence
      quarkus.datasource.jdbc.url: "jdbc:postgresql://postgres:5432/person"
      quarkus.datasource.jdbc.max-size: "10"

      database.provisioning.goals: "-import-demo-data"

      #adapter
      adapter.calleeservice.url: "http://${_Values_host_docker_internal}:50900"
      adapter.timeout: "10000"
      adapter.circuitBreaker.enabled: "true"

      #secrets
      quarkus.datasource.username: "person-service"
      quarkus.datasource.password: "person-service"

      adapter.calleeservice.user: "YWRtaW4="
      adapter.calleeservice.password: "YWRtaW4="

      #log levels
      quarkus.log.level: "INFO"
      quarkus.log.category."org.goafabric".level: "INFO"
      quarkus.log.category."org.flywaydb.core".level: "INFO"
      quarkus.log.category."org.hibernate".level: "INFO"

    depends_on:
      postgres:
        condition: service_healthy

  postgres:
    container_name: ${_Values_root_name}-postgres
    image: postgres:15.1
    restart: 'no'
    ports:
      - 50810:5432
    environment:
      TZ: "Europe/Berlin"
      #secrets
      POSTGRES_USER: "person-service"
      POSTGRES_PASSWORD: "person-service"
      POSTGRES_DB: "person"

    command: postgres -c 'shared_buffers=64MB' -c 'max_connections=30' -c 'shared_preload_libraries=pg_stat_statements'
    healthcheck:
      test: "sh -c pg_isready"
      interval: 10s
      timeout: 5s
      retries: 5
    volumes:
      - pgdata_quarkus:/var/lib/postgresql/data
    networks:
      - ${_Values_root_name}-net

  nginx:
    container_name: ${_Values_root_name}-nginx
    image: nginx:1.22.1
    restart: 'no'
    ports:
      - 8080:80
      - 444:443
    networks:
      - ${_Values_root_name}-net
    volumes:
      - ./nginx/:/etc/nginx/
      - ./ssl/:/etc/ssl/
    depends_on:
      application:
        condition: service_started

volumes:
    tmp:
    applogs:
    pgdata_quarkus:

networks:
  person-service-net:
    driver: bridge